# Generated by Django 5.0.2 on 2024-03-18 22:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_task_attachment_alter_client_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittask',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='submittask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
